/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as IndexRouteImport } from './routes/index'

const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prepare'
    | '/privacy'
    | '/sitemap.xml'
    | '/transparency'
    | '/understand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prepare'
    | '/privacy'
    | '/sitemap.xml'
    | '/transparency'
    | '/understand'
  id:
    | '__root__'
    | '/'
    | '/prepare'
    | '/privacy'
    | '/sitemap.xml'
    | '/transparency'
    | '/understand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrepareRoute: typeof PrepareRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransparencyRoute: typeof TransparencyRoute
  UnderstandRoute: typeof UnderstandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrepareRoute: PrepareRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransparencyRoute: TransparencyRoute,
  UnderstandRoute: UnderstandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
